export default [
  {
    id: 1,
    name: "Janeiro",
    days: 31,
    holidays: [
      { name: "Ano Novo", day: 1 },
      { name: "Dia do Sanitarista", day: 2 },
      { name: "Dia do Hemofílico", day: 3 },
      { name: "Dia Mundial do Braile", day: 4 },
      { name: "Dia Nacional da Tipografia", day: 5 },
      { name: "Dia de Reis", day: 6 },
      { name: "Dia do Leitor", day: 7 },
      { name: "Dia da Fotografia", day: 8 },
      { name: "Dia do Astronauta", day: 9 },
      { name: "Dia de São Gonçalo", day: 10 },
      { name: "Dia de São Teodósio", day: 11 },
      { name: "Dia do Sargento", day: 14 },
      { name: "Dia Oficial do Cabeleireiro", day: 19 },
      { name: "Dia do Farmacêutico", day: 20 },
    ],
  },
  {
    id: 2,
    name: "Fevereiro",
    days: 28,
    holidays: [
      { name: "Dia do Publicitário", day: 1 },
      { name: "Dia de Jesus Cristo", day: 2 },
      { name: "Carnaval", day: 25, changes: true },
      { name: "Quarta-feira de cinzas", day: 26, changes: true },
      { name: "Promulgação da primeira Constituição da República do Brasil", day: 24 },
    ],
  },
  {
    id: 3,
    name: "Março",
    days: 31,
    holidays: [
      { name: "Dia Internacional da Mulher", day: 8 },
      { name: "Dia do Bibliotecário", day: 12 },
      { name: "Dia dos Carecas", day: 14 },
      { name: "Dia do Consumidor", day: 15 },
      { name: "Dia de São Patrício", day: 17 },
      { name: "Dia do Caráter", day: 19 },
      { name: "Dia Mundial do Teatro", day: 27 },
    ],
  },
  {
    id: 4,
    name: "Abril",
    days: 30,
    holidays: [
      { name: "Dia da Mentira", day: 1 },
      { name: "Dia Mundial da Conscientização do Autismo", day: 2 },
      { name: "Dia Nacional do Parkinsoniano", day: 4 },
      { name: "Dia do Corretor", day: 7 },
      { name: "Dia Mundial de Combate ao Câncer", day: 8 },
      { name: "Paixão de Cristo", day: 10, changes: true },
      { name: "Páscoa", day: 10, changes: true },
      { name: "Dia do Desarmamento Infantil", day: 15 },
      { name: "Dia Nacional do Livro Infantil", day: 18 },
      { name: "Dia do Índio", day: 19 },
      { name: "Dia de Tiradentes", day: 21 },
      { name: "Dia do Descobrimento do Brasil", day: 22 },
      { name: "Dia de São Jorge", day: 23 },
      { name: "Dia de Libras", day: 24 },
      { name: "Dia da Educação", day: 28 },
      { name: "Dia Internacional da Dança", day: 29 },
      { name: "Dia Nacional da Mulher", day: 30 },
    ],
  },
  {
    id: 5,
    name: "Maio",
    days: 31,
    holidays: [
      { name: "Dia do Trabalhador", day: 1 },
      { name: "Dia Nacional da Matemática", day: 6 },
      { name: "Dia Mundial do Silêncio", day: 7 },
      { name: "Dia do Artista Plástico Brasileiro", day: 8 },
      { name: "Dia das Mães", day: 10, changes: true },
      { name: "Dia da Abolição da Escravatura", day: 13 },
      { name: "Dia do Cortejo", day: 15 },
      { name: "Dia dos Cientistas", day: 16 },
      { name: "Dia Internacional da Luta Contra à Homofobia", day: 17 },
      { name: "Dia Nacional de Combate ao Abuso e à Exploração Sexual de Crianças e Adolescentes", day: 18 },
      { name: "Dia do Profissional de Física", day: 19 },
      { name: "Dia do Apicultor", day: 22 },
      { name: "Dia do Sol", day: 23 },
      { name: "Dia da Indústria Gráfica", day: 24 },
      { name: "Dia da Indústria e do Industrial", day: 25 },
      { name: "Dia do Profissional Liberal", day: 27 },
      { name: "Dia de Ação pela Saúde da Mulher", day: 28 },
      { name: "Dia do Geógrafo e do Estatístico", day: 29 },
      { name: "Dia do Comissário de Voo", day: 31 },
    ],
  },
  {
    id: 6,
    name: "Junho",
    days: 30,
    holidays: [
      { name: "Dia Mundial do Meio Ambiente", day: 5 },
      { name: "Dia do Cunhado", day: 8 },
      { name: "Dia da Marinha Brasileira", day: 11 },
      { name: "Dia dos Namorados", day: 12 },
      { name: "Dia de Santo Antônio", day: 13 },
      { name: "Dia do Químico", day: 18 },
      { name: "Dia do Cinema Brasileiro", day: 19 },
      { name: "Início do Inverno", day: 21 },
      { name: "Dia Olímpico", day: 23 },
      { name: "Dia de São João", day: 24 },
      { name: "Dia de São Pedro", day: 29 },
    ],
  },
  {
    id: 7,
    name: "Julho",
    days: 31,
    holidays: [
      { name: "Independência da Bahia", day: 2 },
      { name: "Dia Nacional do Pesquisador", day: 8 },
      { name: "Dia Mundial do Rock", day: 13 },
      { name: "Dia dos Homens", day: 15 },
      { name: "Dia do Amigo", day: 20 },
      { name: "Dia dos Avós", day: 26 },
    ],
  },
  {
    id: 8,
    name: "Agosto",
    days: 31,
    holidays: [
      { name: "Dia dos Pais", day: 9, changes: true },
      { name: "Dia do Estudante", day: 11 },
      { name: "Dia Mundial do Canhoto", day: 13 },
      { name: "Dia do Folclore", day: 22 },
      { name: "Dia do Susto", day: 23 },
      { name: "Dia do Soldado", day: 25 },
      { name: "Dia do Psicólogo", day: 27 },
      { name: "Dia do Nutricionista", day: 31 },
    ],
  },
  {
    id: 9,
    name: "Setembro",
    days: 30,
    holidays: [
      { name: "Dia do Profissional de Educação Física", day: 1 },
      { name: "Dia Nacional do Biólogo", day: 3 },
      { name: "Dia da Amazônia", day: 5 },
      { name: "Dia da Proclamação da Independência do Brasil", day: 7 },
      { name: "Dia de Nossa Senhora, Maria, Mãe de Jesus", day: 8 },
      { name: "Dia do Administrador", day: 9 },
      { name: "Dia do Programador", day: 13 },
      { name: "Dia do Cliente", day: 15 },
      { name: "Dia da Árvore", day: 21 },
      { name: "Dia do Contador", day: 22 },
      { name: "Dia da Aurora", day: 23 },
      { name: "Dia do Hipnólogo", day: 25 },
      { name: "Dia Nacional dos Surdos", day: 26 },
      { name: "Dia da Secretaria", day: 30 },
    ],
  },
  {
    id: 10,
    name: "Outubro",
    days: 31,
    holidays: [
      { name: "Dia do Vendedor", day: 1 },
      { name: "Dia do Nordestino", day: 8 },
      { name: "Dia das Crianças", day: 12 },
      { name: "Dia do Professor", day: 15 },
      { name: "Dia do Médico", day: 18 },
      { name: "Dia do Arquivista", day: 20 },
      { name: "Dia do Dentista", day: 25 },
      { name: "Dia do Servidor Público", day: 28 },
      { name: "Dia da Reforma Protestante", day: 31 },
    ],
  },
  {
    id: 11,
    name: "Novembro",
    days: 30,
    holidays: [
      { name: "Dia de Todos os Santos", day: 1 },
      { name: "Dia de Finados", day: 2 },
      { name: "Dia do Radialista", day: 7 },
      { name: "Dia do Diretor de Escola", day: 12 },
      { name: "Dia Nacional da Alfabetização", day: 14 },
      { name: "Dia da Proclamação da República", day: 15 },
      { name: "Dia da Bandeira Nacional", day: 19 },
      { name: "Dia da Consciência Negra", day: 20 },
      { name: "Dia do Engenheiro Eletricista", day: 23 },
    ],
  },
  {
    id: 12,
    name: "Dezembro",
    days: 31,
    holidays: [
      { name: "Dia do Orientador Educacional", day: 4 },
      { name: "Dia Nacional da Silvicultura", day: 7 },
      { name: "Dia da Justiça", day: 8 },
      { name: "Dia do Fonoaudiólogo", day: 9 },
      { name: "Dia da Bíblia", day: 10 },
      { name: "Dia do Engenheiro Civil", day: 11 },
      { name: "Dia do Museólogo", day: 18 },
      { name: "Início do Verão", day: 22 },
      { name: "Natal", day: 25 },
      { name: "Réveillon", day: 31 },
    ],
  },
];
